# Generated by Django 4.2.3 on 2023-07-14 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_collection', models.CharField(choices=[('men', 'men'), ('women', 'women')], max_length=100)),
                ('Product_category', models.CharField(choices=[('jeans', 'jeans'), ('shirt', 'shirt')], max_length=100)),
                ('product_size', models.CharField(choices=[('m', 'm'), ('l', 'l')], max_length=100)),
                ('product_color', models.CharField(choices=[('red', 'red'), ('black', 'black'), ('blue', 'blue')], max_length=100)),
                ('product_price', models.PositiveIntegerField()),
                ('product_description', models.TextField()),
                ('product_image', models.ImageField(upload_to='product_image/')),
            ],
        ),
        migrations.CreateModel(
            name='UserCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20)),
                ('usertype', models.CharField(choices=[('user', 'user'), ('seller', 'seller')], max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usercreate')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usercreate'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product_qty', models.PositiveIntegerField()),
                ('total_prie', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usercreate')),
            ],
        ),
    ]
