# Generated by Django 4.2.3 on 2023-07-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_usercreate_gender_alter_usercreate_usertype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.CharField(choices=[('m', 'medium'), ('l', 'l')], max_length=100),
        ),
    ]
