# Generated by Django 4.2.3 on 2023-07-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_product_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.CharField(choices=[('m', 'm'), ('l', 'l')], max_length=100),
        ),
    ]
