# Generated by Django 4.2.3 on 2023-08-01 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_product_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total_prie',
            new_name='total_price',
        ),
    ]
