# Generated by Django 4.2.3 on 2023-08-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_total_prie_cart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_collection',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women')], max_length=100),
        ),
    ]
