# Generated by Django 4.2.3 on 2023-08-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_product_product_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_color',
            field=models.CharField(choices=[('red', 'Red'), ('black', 'Black'), ('blue', 'Blue')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.CharField(choices=[('m', 'M'), ('l', 'L')], max_length=100),
        ),
    ]
