# Generated by Django 4.2.3 on 2023-08-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_product_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_collection',
            field=models.CharField(choices=[('Men', 'Men'), ('women', 'Women')], max_length=100),
        ),
    ]
