# Generated by Django 4.2.3 on 2023-08-08 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_product_product_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_collection',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women')], max_length=100),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usercreate')),
            ],
        ),
    ]
